# Generated by Django 3.2 on 2022-03-23 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_value', models.CharField(max_length=32)),
                ('parent_attribute_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.categoryattribute')),
            ],
        ),
    ]
