# Generated by Django 3.2 on 2022-03-23 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_categoryattributevalue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryattributevalue',
            old_name='parent_attribute_id',
            new_name='parent_attribute',
        ),
    ]
