# Generated by Django 3.2 on 2022-03-26 13:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_productattribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='value',
            field=models.CharField(default=django.utils.timezone.now, max_length=32),
            preserve_default=False,
        ),
    ]
