# Generated by Django 3.2 on 2022-03-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20220326_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattributevalue',
            name='parent_attribute',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='Product_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_image'),
        ),
        migrations.DeleteModel(
            name='ProductAttribute',
        ),
        migrations.DeleteModel(
            name='ProductAttributeValue',
        ),
    ]
