# Generated by Django 3.2 on 2022-03-27 10:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='product_image'),
            preserve_default=False,
        ),
    ]
