# Generated by Django 3.2 on 2022-03-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_alter_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Product_image',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product'),
        ),
    ]
