# Generated by Django 3.2 on 2022-03-30 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_auto_20220328_0859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryattributevalue',
            old_name='parent_attribute',
            new_name='category_attribute',
        ),
    ]
