# Generated by Django 3.2 on 2022-04-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_auto_20220404_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_attribute_value',
            field=models.ManyToManyField(to='shop.CategoryAttributeValue'),
        ),
    ]
