# Generated by Django 3.2 on 2022-04-04 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_product_category_attribute_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='shop.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_attribute_value',
            field=models.ManyToManyField(blank=True, null=True, to='shop.CategoryAttributeValue'),
        ),
    ]
