# Generated by Django 3.2 on 2022-04-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_auto_20220404_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, to='shop.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_attribute_value',
            field=models.ManyToManyField(blank=True, to='shop.CategoryAttributeValue'),
        ),
    ]
