# Generated by Django 3.2 on 2022-04-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_alter_productattribute_attribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='value',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='attribute_value',
            field=models.ManyToManyField(to='shop.CategoryAttributeValue'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='category',
            field=models.ManyToManyField(to='shop.Category'),
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='attribute',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='attribute',
            field=models.ManyToManyField(to='shop.CategoryAttribute'),
        ),
    ]
