# Generated by Django 3.2 on 2022-04-04 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_auto_20220404_0721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='attribute',
        ),
    ]
