# Generated by Django 3.2 on 2022-04-04 07:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_remove_productattribute_attribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='category',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='attribute',
            field=models.CharField(default=django.utils.timezone.now, max_length=32),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='attribute_value',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='attribute_value',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
