# Generated by Django 3.2 on 2022-04-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_auto_20220404_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryattribute',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200, null=True, unique=True),
        ),
    ]
