# Generated by Django 3.2 on 2022-04-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_category_icon_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgallery',
            name='alt_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
