# Generated by Django 3.2 on 2022-05-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0048_auto_20220506_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='noindex',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
