# Generated by Django 3.2 on 2022-05-12 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0050_auto_20220511_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryattribute',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_category', to='shop.category'),
        ),
        migrations.AlterField(
            model_name='categoryattributevalue',
            name='category_attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_category_attribute', to='shop.categoryattribute'),
        ),
        migrations.AlterField(
            model_name='productcategoryattributevalue',
            name='category_attribute_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_category_attribute_value', to='shop.categoryattributevalue'),
        ),
        migrations.AlterField(
            model_name='productcategoryattributevalue',
            name='in_header',
            field=models.BooleanField(default=False),
        ),
    ]
