# Generated by Django 3.2 on 2022-05-12 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0051_auto_20220512_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategoryattributevalue',
            name='category_attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.categoryattribute'),
        ),
    ]
