# Generated by Django 3.2 on 2022-05-12 13:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0052_productcategoryattributevalue_category_attribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategoryattributevalue',
            name='category_attribute',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.categoryattribute'),
            preserve_default=False,
        ),
    ]
