# Generated by Django 3.2 on 2022-05-13 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0053_alter_productcategoryattributevalue_category_attribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('product_rel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_related', to='shop.product')),
            ],
        ),
    ]
