# Generated by Django 3.2 on 2022-05-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0055_remove_productgallery_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
