# Generated by Django 3.2 on 2022-05-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0056_auto_20220515_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgallery',
            name='id',
            field=models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False, unique=True),
        ),
    ]
