# Generated by Django 3.2 on 2022-05-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0057_alter_productgallery_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={},
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
