# Generated by Django 3.2 on 2022-05-22 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0061_categorymeta_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymeta',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', unique=True),
        ),
    ]
