# Generated by Django 3.2 on 2022-05-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0062_alter_categorymeta_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymeta',
            name='special_brand',
            field=models.JSONField(blank=True, max_length=800, null=True),
        ),
    ]
