# Generated by Django 3.2 on 2022-05-28 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0063_categorymeta_special_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategoryattributevalue',
            name='category_attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.categoryattribute'),
        ),
        migrations.AlterField(
            model_name='productcategoryattributevalue',
            name='category_attribute_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_category_attribute_value', to='shop.categoryattributevalue'),
        ),
    ]
