# Generated by Django 3.2 on 2022-06-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0066_auto_20220620_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='in_header',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
