# Generated by Django 3.2 on 2022-06-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0067_productattribute_in_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='en_title',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
