# Generated by Django 3.2 on 2022-06-24 08:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0070_auto_20220623_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalattribute',
            name='color_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='globalattribute',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
